import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["greek"] });

export const metadata = {
  title: "Next potfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <head>
        {/* <link rel="icon" href="https://www.youtube.com/s/desktop/7c0eb0c2/img/favicon_32x32.png" sizes="any" /> */}
      </head>
      <body className={inter.className}>{children}
      </body>
    </html>
  );
}
